<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Foundation\ChronicleDB.Core\ChronicleDB.Core.csproj" />
    <ProjectReference Include="..\..\Observability\ChronicleDB.Diagnostics\ChronicleDB.Diagnostics.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
